name: diplom
channels:
  - gurobi
  - defaults
dependencies:
  - python=3.10
  - gurobi
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - jupyter
  - jupyterlab
  - ipywidgets
  - pip
  - pip:
      - git+https://github.com/takazawa/newsvendor-model
