name: diplom
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - numpy
  - pandas
  - polars
  - matplotlib
  - seaborn
  - ipykernel
  - jupyter
  - notebook
  - google-cloud-bigquery
  - pyarrow=14.0.1  # Ensure compatibility with BigQuery
  - tqdm
  - pip