name: diplom
channels:
  - defaults
  - conda-forge
  - gurobi
dependencies:
  - python=3.9
  - gurobi
  - numpy
  - pandas
  - matplotlib
  - ipykernel
  - pip
  - pip:
      - git+https://github.com/takazawa/newsvendor-model