CREATE OR REPLACE TABLE `brain-flash-dev.dagster_common.CN_data_to_fetch` AS
WITH
  cte_select_n_items AS (
  SELECT
    TEST_ITEM_COMMUNICATIONKEY,
    MAX(NA_COUNT/TWIN_COUNT) AS NA_QUOTA
  FROM
    `brain-flash-dev.dagster_common.CN_twin_data` data
  WHERE TWIN_COUNT >= 4
  GROUP BY TEST_ITEM_COMMUNICATIONKEY
  ORDER BY NA_QUOTA ASC, MIN(TWIN_COUNT) DESC
  LIMIT(100)
   ),
  cte_top_data AS(
    SELECT *
    FROM cte_select_n_items
    JOIN `brain-flash-dev.dagster_common.CN_twin_data` data
    USING (TEST_ITEM_COMMUNICATIONKEY)
  ),
  cte_test_window AS(
    SELECT *
    FROM cte_top_data
    WHERE TEST_ITEM_COMMUNICATIONKEY = TWIN_ITEM_COMMUNICATIONKEY
    AND CALENDAR_DATE BETWEEN FIRST_ANSPRACHE_DATE AND LEAST(FIRST_ANSPRACHE_DATE+364, FIRST_SOLDOUT_DATE)
  ),
  cte_twin_window AS(
    SELECT *
    FROM cte_top_data
    WHERE TEST_ITEM_COMMUNICATIONKEY != TWIN_ITEM_COMMUNICATIONKEY
    AND CALENDAR_DATE BETWEEN FIRST_ANSPRACHE_DATE-364 AND FIRST_ANSPRACHE_DATE - 364 + DATE_DIFF(LEAST(FIRST_ANSPRACHE_DATE+364, FIRST_SOLDOUT_DATE),FIRST_ANSPRACHE_DATE, DAY)
  )

SELECT
  *,
  DATE_DIFF(LEAST(FIRST_ANSPRACHE_DATE+364, FIRST_SOLDOUT_DATE), FIRST_ANSPRACHE_DATE, DAY) AS TEST_PERIOD,
  DATE_DIFF(FIRST_ANSPRACHE_DATE - 364 + DATE_DIFF(LEAST(FIRST_ANSPRACHE_DATE+364, FIRST_SOLDOUT_DATE),FIRST_ANSPRACHE_DATE, DAY), FIRST_ANSPRACHE_DATE-364, DAY) TWIN_PERIOD
FROM
  cte_test_window
UNION ALL
SELECT *,
  DATE_DIFF(LEAST(FIRST_ANSPRACHE_DATE+364, FIRST_SOLDOUT_DATE), FIRST_ANSPRACHE_DATE, DAY) AS TEST_PERIOD,
  DATE_DIFF(FIRST_ANSPRACHE_DATE - 364 + DATE_DIFF(LEAST(FIRST_ANSPRACHE_DATE+364, FIRST_SOLDOUT_DATE),FIRST_ANSPRACHE_DATE, DAY), FIRST_ANSPRACHE_DATE-364, DAY) TWIN_PERIOD
FROM
  cte_twin_window

ORDER BY TEST_ITEM_COMMUNICATIONKEY, TWIN_ITEM_COMMUNICATIONKEY, CALENDAR_DATE

--if hardfiltered by soldout date the cut wont exactly appy and should be adjusted to soldout date instead of last ansprache date