CREATE OR REPLACE TABLE `brain-flash-dev.dagster_common.CN_data_to_fetch` AS
WITH
  cte_select_n_items AS (
  SELECT
    DISTINCT TEST_ITEM_COMMUNICATIONKEY
  FROM
    `brain-flash-dev.dagster_common.CN_twin_data`
  LIMIT
    (100) )
SELECT
  *,
  LEAST(EXTRACT(DAY
    FROM (LAST_ANSPRACHE_DATE - FIRST_ANSPRACHE_DATE)), 364) AS PERIOD_LENGHT
FROM
  cte_select_n_items item_selection
JOIN
  `brain-flash-dev.dagster_common.CN_twin_data`
USING
  (TEST_ITEM_COMMUNICATIONKEY)
WHERE
  TWIN_COUNT >= 4 AND
  CALENDAR_DATE BETWEEN FIRST_ANSPRACHE_DATE AND LEAST(FIRST_ANSPRACHE_DATE+364, LAST_ANSPRACHE_DATE)
  OR CALENDAR_DATE BETWEEN FIRST_ANSPRACHE_DATE-365 AND FIRST_ANSPRACHE_DATE - 365 + LEAST(DATE_DIFF(LAST_ANSPRACHE_DATE,FIRST_ANSPRACHE_DATE,DAY), 364)