CREATE OR REPLACE TABLE `brain-flash-dev.dagster_common.CN_data_to_fetch` AS
WITH
  cte_select_n_items AS (
  SELECT
    DISTINCT TEST_ITEM_COMMUNICATIONKEY
  FROM
    `brain-flash-dev.dagster_common.CN_twin_data`
  WHERE TWIN_COUNT >= 4
  LIMIT
    (100) ),
  cte_top_data AS(
    SELECT *
    FROM cte_select_n_items
    JOIN `brain-flash-dev.dagster_common.CN_twin_data` data
    USING (TEST_ITEM_COMMUNICATIONKEY)
  ),
  cte_test_window AS(
    SELECT *
    FROM cte_top_data
    WHERE TEST_ITEM_COMMUNICATIONKEY = TWIN_ITEM_COMMUNICATIONKEY
    AND CALENDAR_DATE BETWEEN FIRST_ANSPRACHE_DATE AND LEAST(FIRST_ANSPRACHE_DATE+363, LAST_ANSPRACHE_DATE)
  ),
  cte_twin_window AS(
    SELECT *
    FROM cte_top_data
    WHERE TEST_ITEM_COMMUNICATIONKEY != TWIN_ITEM_COMMUNICATIONKEY
    AND CALENDAR_DATE BETWEEN FIRST_ANSPRACHE_DATE-363 AND FIRST_ANSPRACHE_DATE - 363 + LEAST(DATE_DIFF(LAST_ANSPRACHE_DATE,FIRST_ANSPRACHE_DATE,DAY), 362)
  )
SELECT
  *,
  LEAST(EXTRACT(DAY
    FROM (LAST_ANSPRACHE_DATE - FIRST_ANSPRACHE_DATE)), 363) AS TEST_PERIOD,
  DATE_DIFF(LEAST(FIRST_ANSPRACHE_DATE+363, LAST_ANSPRACHE_DATE), FIRST_ANSPRACHE_DATE-364, DAY) AS OBS_PERIOD
FROM
  cte_test_window
UNION ALL
SELECT *,
  LEAST(EXTRACT(DAY
    FROM (LAST_ANSPRACHE_DATE - FIRST_ANSPRACHE_DATE)), 363) AS TEST_PERIOD,
  DATE_DIFF(LEAST(FIRST_ANSPRACHE_DATE+363, LAST_ANSPRACHE_DATE), FIRST_ANSPRACHE_DATE-364, DAY) AS OBS_PERIOD
FROM
  cte_twin_window

  --die eingrenzungen der Perioden sind noch nicht ganz fertig, aber ich hab grad kein Bock mehr auf das Rumgefummel